name: ci
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      image-tag:
        description: "image tag"
        value: ${{ jobs.build-and-test.outputs.image-tag }}
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # need this for OIDC
      contents: read
    environment: main
    outputs:
      image-tag: ${{ steps.set-image-tag.outputs.IMAGE_TAG }} 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # TODO
      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::129361430828:role/apmlify_actions_hackpod_iam_role
          role-session-name: GitHubActions
          role-duration-seconds: 3600
          mask-aws-account-id: true
      # CloudFormation Lint
      # CloudFormation Static Analysis
      # Build docker images
      # Set new image tag
      # Scan new image
      # Generate summary